### PR TITLE
Update conway.hy to work with hy 0.13

### PR DESCRIPTION
**Pull request by jgkamat**
Sorry if there are any style/functionality issues, I'm very new to hy :smile:.

All I did was remove the `let` statments and replace them with `setv` calls.

### CODE REVIEW

**Comment by Kodiologist** [comment]
This project doesn't seem to have a maintainer. In fact, the last commit is from 2013. Any volunteers?

**Comment by tuturto** [comment]
I volunteer

**Comment by Kodiologist** [comment]
Congratulations, you're the maintainer! :)

**Comment by tuturto** [comment]
Thank you jgkamat

**Pull request merged**
